smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -329,7 +329,70 @@ jobs:
 
       - destroy-environment
       - revert-migrations
+  smoke-test:
+    docker:
+      # Lightweight Docker image 
+      - image: cimg/base:stable
+    steps:
+      # Checkout code from git
+      - checkout
+      - install_awscli
+      - install_nodejs
 
+
+      - run:
+          name: Backend smoke test.
+          command: |
+           export BACKEND_IP=$(aws ec2 describe-instances \
+             --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
+             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+             --output text)
+           export API_URL="http://${BACKEND_IP}:3030"
+           echo ${API_URL}
+           if curl -s $API_URL/api/status | grep "ok"
+           then
+            exit 0
+           else
+            exit 1
+           fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/#/employees
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+            then
+              exit 1
+            else
+              exit 1
+            fi
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+      - revert-migrations
+  cloudfront-update:
+   docker:
+     - image: cimg/base:stable
+   steps:
+     - checkout
+     - install_nodejs
+     - install_awscli
+     - run:
+         name: Save Old Workflow ID to kvdb.io
+         command: |
+           export OLD_WORKFLOW_ID=$(aws cloudformation \
+                     list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                     --no-paginate --output text)
+           echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
+           curl https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d "${OLD_WORKFLOW_ID}"
+     - run:
+         name: Update cloudfront distribution
+         command: |
+           aws cloudformation deploy \
+             --template-file .circleci/files/cloudfront.yml \
+             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+             --stack-name InitialStack
+     - destroy-environment
+     - revert-migrations
 workflows:
   default:
     jobs:
@@ -355,4 +418,6 @@ workflows:
       - deploy-frontend:
           requires: [run-migrations]
       - deploy-backend:
-          requires: [run-migrations] 
+          requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
